# Nome da aplicação
spring.application.name=desafio-votacao

# Configuração do Banco H2 (em memória)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o Console do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostra o SQL no terminal (ajuda muito no debug de Sênior)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update