logging:
  level:
    com.dbserver.votacao: INFO
    org.hibernate.SQL: DEBUG # Isso mostra o SQL limpo
    org.hibernate.orm.results: INFO # Volte para INFO para sumir com aqueles gráficos gigantes
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE # DEBUG Isso vai mostrar os MAPS

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  profiles:
    active: dev
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 50
        order_inserts: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Configurações customizadas da aplicação e integrações
app:
  integration:
    user-info:
      url: "https://user-info.herokuapp.com/users"
    cpf-url: "https://user-info.herokuapp.com/users/"

---
# Profile de Desenvolvimento (Postgres Docker)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/db_votacao
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

---
# Profile de Teste (H2 in-memory)
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop